// <auto-generated />
using Decibels.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Decibels.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240717142403_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Decibels.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Microphones"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Guitars"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Drums"
                        });
                });

            modelBuilder.Entity("Decibels.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Yamaha YDM707 dynamic microphone combines decades of Yamaha's expertise in musical technologies with advanced design to deliver unparalleled sound quality.",
                            Name = "Yamaha YDM707 B Dynamic Vocal Microphone",
                            Price = 169m
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Shure SM7B microphone has been the industry standard in radio studios for years. ",
                            Name = "Shure SM7B Dynamic Vocal Studio Microphone",
                            Price = 381m
                        },
                        new
                        {
                            Id = 3,
                            Description = "When you say Sennheiser, you actually mean the E 835! What the SM58 is to Shure, the E 835 is to Sennheiser, and it remains a battle of the titans for the best place in the stage branch!",
                            Name = "Sennheiser E 935 dynamic vocal microphone",
                            Price = 158m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Are you used to an electric guitar or western guitar, but would you still like to have a nylon-string classical guitar as well? Then this Cordoba Fusion 5 Edge Burst is an excellent option.",
                            Name = "Cordoba Fusion 5 Edge Burst Electric Acoustic Classical Guitar",
                            Price = 509m
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Schecter C-1 FR S SLS Elite can rightly be called the flagship of the series. The basis of this modern electric guitar is formed by an ash (swamp ash) solid body with a beautiful flame maple top.",
                            Name = "Schecter C-1 FR S SLS Elite Blood Burst Electric Guitar with Sustainiac",
                            Price = 1789m
                        },
                        new
                        {
                            Id = 6,
                            Description = "What is a Marshall without its classic gold-black finish? That's right, nothing! That's why the new MG series is back in this colour scheme with the MG50FX guitar amplifier combo as its showpiece.",
                            Name = "Marshall MG50FX 50 Watt 1x12 Transistor Guitar Amplifier Combo",
                            Price = 365m
                        },
                        new
                        {
                            Id = 7,
                            Description = "With the Pearl RS505BC Roadshow, the aspiring drummer has everything they need: a drum kit, stands, pedals, cymbals, sticks and a stick bag included! The journey of a successful drumming career starts here.",
                            Name = "Pearl RS505BC/C31 Roadshow 5-piece drum kit with 3-piece Sabian cymbal set",
                            Price = 799m
                        },
                        new
                        {
                            Id = 8,
                            Description = "The next generation of drummers will go far with the Roland TD-02KV. This compact electronic drum kit has the expressive sounds we know from much more expensive V-Drums but then packed into sixteen ready-to-play sets.",
                            Name = "Roland TD-02KV V-Drums electronic drum kit",
                            Price = 499m
                        },
                        new
                        {
                            Id = 9,
                            Description = "In the new series of Export drum sets, Pearl delivers this five-piece drum set. Pearl Export drum sets are still the best-selling kits in the world and are well known for their excellent price-quality ratio.",
                            Name = "Pearl EXX705NBR/C704 Export Black Cherry Glitter 5-piece drum kit",
                            Price = 1089m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
