# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - decibels-music

on:
  push:
    branches:
      - main
      - develop # <--- ADDED: This line ensures the workflow triggers on pushes to 'develop'
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.GITHUB_WORKSPACE}}\myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.GITHUB_WORKSPACE}}\myapp

  # Job for deploying to Production environment (triggered only by pushes to 'main')
  deploy-production:
    runs-on: windows-latest
    needs: build
    # This condition is crucial: only run this job if the branch is 'main'
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'Production' # This references an environment configured in GitHub (optional but good practice)
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure login
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_74454F2B185242C1B0DE4318FF8D20FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD3B7D3C65224EFCAA2A577449CEB838 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40BEB970A7694C4CB7C7EDFF5FC80941 }}

      - name: Deploy to Azure Web App (Production Slot)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'decibels-music'
          slot-name: 'Production' # Targets the main production slot
          package: .

  # NEW JOB: Deploy to Staging environment (triggered only by pushes to 'develop')
  deploy-staging:
    runs-on: windows-latest
    needs: build
    # This condition is crucial: only run this job if the branch is 'develop'
    if: github.ref == 'refs/heads/develop'
    environment:
      name: 'Staging' # You can define this environment in GitHub settings if you want to add protection rules later
      url: https://decibels-music-staging.azurewebsites.net/ # <--- IMPORTANT: REPLACE THIS with actual Staging slot URL
    permissions:
      id-token: write # Required for Azure login
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_74454F2B185242C1B0DE4318FF8D20FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD3B7D3C65224EFCAA2A577449CEB838 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40BEB970A7694C4CB7C7EDFF5FC80941 }}

      - name: Deploy to Azure Web App (Staging Slot)
        id: deploy-to-staging-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'decibels-music'
          slot-name: 'Staging' # Targets your newly created Staging slot
          package: .
